name: color_shader
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:       # Required for every Flutter project
      sdk: flutter    

dev_dependencies:
  # flutter:       # Required for every Flutter project
  #     sdk: flutter
  lints: ^2.0.0
  test: ^1.16.0
