name: color_hue_n_tint
description: A package to gennerate Color Shading
version: 1.0.2
homepage: https://github.com/athiruj/color_hue_n_tint

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter: # Required for every Flutter project
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
